version: "3"
services:
  springboot-app:
    image: springboot-app
    build: .
    ports:
      - "8000-8999:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: ramadan
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123456